# Generated by Django 4.2.18 on 2025-11-21 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_ecommerce', '0002_product_created_at_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
