# Generated by Django 4.2.18 on 2025-11-21 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_ecommerce', '0006_shippingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestockSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_quantity', models.IntegerField(verbose_name='建议补货数量')),
                ('priority', models.IntegerField(default=5, verbose_name='优先级(1-10)')),
                ('reason', models.TextField(verbose_name='补货理由')),
                ('status', models.CharField(default='PENDING', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_suggestions', to='core_ecommerce.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '补货建议',
                'verbose_name_plural': '补货建议',
            },
        ),
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.IntegerField(default=10, verbose_name='预警阈值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_alerted_at', models.DateTimeField(blank=True, null=True, verbose_name='最后预警时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core_ecommerce.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '库存预警',
                'verbose_name_plural': '库存预警',
            },
        ),
    ]
